### ISSUE TITLE
Link to sicp-study => HTTP 404

### ISSUE THREAD

**Issue by elimisteve** [vu3rdd/sicp#2]
Thanks for creating this repo; Racket and Clojure are my 2 favorite Lisp dialects.

https://rkrishnan.org/2010/03/14/sicp-study/ throws a 404.  Hopefully you can bring that blog post back up, or link to something like https://web.archive.org/web/20130821055058/http://rkrishnan.org/blog/2011/12/23/sicp-challenge-progress/ , except the correct link, which I could not quite find :-).

**Comment by vu3rdd** [comment]
Glad you liked it. I am still somewhere on chapter 4. Read parts of chapter 5, but I think I should restart from where I left.

The link is probably here: https://web.archive.org/web/20130820130146/http://rkrishnan.org/2010/03/14/sicp-study/ I will fix it now. Thanks.

**Comment by vu3rdd** [comment]
Fixed by 1d3ec75bd21c57a857310fb439a490754991d0b6
